### ISSUE TITLE
hitomi.la parsing exception direct download and e-hentai mirror option

### ISSUE THREAD

**Issue by Dystasia** [HDoujinDownloader/HDoujinDownloader#136]
Looks like something changed in the response from hitomi.la that is in turn making page parsing fail.

This is happening in both direct downloads and e-hentai mirror option downloads.

### Direct Download:
20:44:43 hitomi.la   [!] An error occurred while getting the page count: Jint.Parser.ParserException: Line 171: Unexpected token >
   at Jint.Parser.JavaScriptParser.ThrowError(Token token, String messageFormat, Object[] arguments)
   at Jint.Parser.JavaScriptParser.ParsePrimaryExpression()
   at Jint.Parser.JavaScriptParser.ParseLeftHandSideExpressionAllowCall()
   at Jint.Parser.JavaScriptParser.ParsePostfixExpression()
   at Jint.Parser.JavaScriptParser.ParseUnaryExpression()
   at Jint.Parser.JavaScriptParser.ParseBinaryExpression()
   at Jint.Parser.JavaScriptParser.ParseConditionalExpression()
   at Jint.Parser.JavaScriptParser.ParseAssignmentExpression()
   at Jint.Parser.JavaScriptParser.ParseAssignmentExpression()
   at Jint.Parser.JavaScriptParser.ParseArguments()
   at Jint.Parser.JavaScriptParser.ParseNewExpression()
   at Jint.Parser.JavaScriptParser.ParseLeftHandSideExpressionAllowCall()
   at Jint.Parser.JavaScriptParser.ParsePostfixExpression()
   at Jint.Parser.JavaScriptParser.ParseUnaryExpression()
   at Jint.Parser.JavaScriptParser.ParseBinaryExpression()
   at Jint.Parser.JavaScriptParser.ParseConditionalExpression()
   at Jint.Parser.JavaScriptParser.ParseAssignmentExpression()
   at Jint.Parser.JavaScriptParser.ParseVariableDeclaration(String kind)
   at Jint.Parser.JavaScriptParser.ParseVariableDeclarationList(String kind)
   at Jint.Parser.JavaScriptParser.ParseConstLetDeclaration(String kind)
   at Jint.Parser.JavaScriptParser.ParseStatementList()
   at Jint.Parser.JavaScriptParser.ParseBlock()
   at Jint.Parser.JavaScriptParser.ParseStatement()
   at Jint.Parser.JavaScriptParser.ParseIfStatement()
   at Jint.Parser.JavaScriptParser.ParseStatement()
   at Jint.Parser.JavaScriptParser.ParseStatementList()
   at Jint.Parser.JavaScriptParser.ParseBlock()
   at Jint.Parser.JavaScriptParser.ParseStatement()
   at Jint.Parser.JavaScriptParser.ParseIfStatement()
   at Jint.Parser.JavaScriptParser.ParseStatement()
   at Jint.Parser.JavaScriptParser.ParseSourceElements()
   at Jint.Parser.JavaScriptParser.ParseProgram()
   at Jint.Parser.JavaScriptParser.Parse(String code, ParserOptions options)
   at Jint.Engine.Execute(String source)
   at EeIWRBULEQSRLvruwoaPevguDBCv.HVmziMfpjUEdXHcPbqpWAZsuoBvpA(String )
   at lambda_method(Closure , Object , Object[] )
   at MoonSharp.Interpreter.Interop.MethodMemberDescriptor.Execute(Script script, Object obj, ScriptExecutionContext context, CallbackArguments args)
   at MoonSharp.Interpreter.Interop.OverloadedMethodMemberDescriptor.<>c__DisplayClass33_0.<GetCallback>b__0(ScriptExecutionContext context, CallbackArguments args)
   at MoonSharp.Interpreter.Execution.VM.Processor.Internal_ExecCall(Int32 argsCount, Int32 instructionPtr, CallbackFunction handler, CallbackFunction continuation, Boolean thisCall, String debugText, DynValue unwindHandler)
   at MoonSharp.Interpreter.Execution.VM.Processor.Processing_Loop(Int32 instructionPtr)
   at MoonSharp.Interpreter.Execution.VM.Processor.Call(DynValue function, DynValue[] args)
   at aOIakMeUQAWaPwkykDZRRNUetBRUA.fpubolhKTywfKMtuGOtujCJvdwsl(xREJtEUmCvvIaiPQkGHUDAMkKAyI , UwSJSMnpkaihAbKpRbTbGkDiHkBs )
   at aOIakMeUQAWaPwkykDZRRNUetBRUA.nDhFLXQLKtrxeDjFcTRvBuOBcpNj(UwSJSMnpkaihAbKpRbTbGkDiHkBs )
   at aOIakMeUQAWaPwkykDZRRNUetBRUA.ZhRcAhrXMFpjCqccRTebLWHPMzZF(NLbBIGLvDzsxYMNYYOlmclXjTHGQ , AJQZvLcLfIgpZNOECrXTSSeGSunN )

### e-hentai mirror:
Trying mirror: https://hitomi.la/galleries/xxxxxxxx.html
18:57:56 page grabbe [x] Jint.Parser.ParserException: Line 171: Unexpected token >
   at mCJWeXqYITfqvCAjPGQhChaNcmOG.fpubolhKTywfKMtuGOtujCJvdwsl(IEnumerable`1 , xREJtEUmCvvIaiPQkGHUDAMkKAyI , UwSJSMnpkaihAbKpRbTbGkDiHkBs )
   at JDUEsrmSXZMXbesGbJdUGfxWAhwH.fpubolhKTywfKMtuGOtujCJvdwsl(String& )

**Comment by Dystasia** [comment]
I would help fix the Lua but the entire script is encrypted. How can I decrypt it?

**Comment by HDoujinDownloader** [comment]
It should be working now with the fix I just uploaded for hitomi.la. Give it a shot, and let me know if you continue to have problems.

> I would help fix the Lua but the entire script is encrypted. How can I decrypt it?

I know, sorry about that. I had to obfuscate it because they were intentionally breaking it a while ago.
