### ISSUE TITLE
FlareSolverr: Failed to connect to FlareSolverr

### ISSUE THREAD

**Issue by tazibal** [HDoujinDownloader/HDoujinDownloader#230]
HDoujin.Downloader-2023.6.24.0-rc.10-win

When I try to download from nhentai.net (but I think the problem is independent on a site) I got this error everytime . Also tried another PC, same problem. I checked also if port 8191 isn't blocked, but isn't.

When I try tu run just the `flaresolverr.exe` I get the same error as you can see in the log below on the row `21:40:50 flaresolver [i] Launching web browser...` and below.

Thanks for help :) 

> 21:40:49 queue       [i] Attempting to enqueue https://nhentai.net/g/466168/
21:40:49 hdoujinchal [i] Using FlareSolverrChallengeHandler
21:40:49 flaresolver [i] Starting FlareSolverr service
21:40:49 flaresolver [i] Starting FlareSolverr process
21:40:50 flaresolver [i] FlareSolverr 3.2.1
21:40:50 flaresolver [i] Testing web browser installation...
21:40:50 flaresolver [i] Platform: Windows-10-10.0.19045-SP0
21:40:50 flaresolver [i] Chrome / Chromium path: C:\Program Files\Google\Chrome\Application\chrome.exe
21:40:50 flaresolver [i] Chrome / Chromium major version: 115
21:40:50 flaresolver [i] Launching web browser...
21:40:50 flaresolver [x] Traceback (most recent call last):
21:40:50 flaresolver [x]   File "utils.py", line 207, in get_user_agent
21:40:50 flaresolver [x]   File "utils.py", line 93, in get_webdriver
21:40:50 flaresolver [x]   File "undetected_chromedriver\__init__.py", line 247, in __init__
21:40:50 flaresolver [x]   File "undetected_chromedriver\patcher.py", line 124, in auto
21:40:50 flaresolver [x]   File "undetected_chromedriver\patcher.py", line 145, in fetch_release_number
21:40:50 flaresolver [x]   File "urllib\request.py", line 216, in urlopen
21:40:50 flaresolver [x]   File "urllib\request.py", line 525, in open
21:40:50 flaresolver [x]   File "urllib\request.py", line 634, in http_response
21:40:50 flaresolver [x] 
21:40:50 flaresolver [x]   File "urllib\request.py", line 496, in _call_chain
21:40:50 flaresolver [x]   File "urllib\request.py", line 643, in http_error_default
21:40:50 flaresolver [x] 404: Not Found
21:40:50 flaresolver [x] During handling of the above exception, another exception occurred:
21:40:50 flaresolver [x] Traceback (most recent call last):
21:40:50 flaresolver [x]   File "F:\Users\Squidy\source\repos\Gsemac.Net.Cloudflare\src\Gsemac.Net.Cloudflare.FlareSolverr\build\FlareSolverr\src\flaresolverr.py", line 102, in <module>
21:40:50 flaresolver [x]   File "flaresolverr_service.py", line 72, in test_browser_installation
21:40:50 flaresolver [x]   File "utils.py", line 211, in get_user_agent
21:40:50 flaresolver [x] getting browser User-Agent. HTTP Error 404: Not Found
21:40:50 flaresolver [x] [23440] Failed to execute script 'flaresolverr' due to unhandled exception!
21:40:50 flaresolver [x] Exception ignored in: <function Patcher.__del__ at 0x000001DBBFE320C0>
21:40:50 flaresolver [x] Traceback (most recent call last):
21:40:50 flaresolver [x]   File "undetected_chromedriver\patcher.py", line 272, in __del__
21:40:50 flaresolver [x] OSError: [WinError 6] The handle is invalid
21:40:50 flaresolver [x] Failed to start FlareSolverr process
21:40:54 hdoujinchal [x] System.Net.WebException: The challenge solver threw an exception. ---> TeRDIggEPVtUxEYNZXRKlAWipSbEA: Failed to connect to FlareSolverr. Make sure that FlareSolverr is running on port 8191. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8191
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at NfiBUnEqtckatHAlrMRgwRdowkZIA.Gsemac.Net.IWebClient.UploadString(Uri address, String data)
   at fcYiqTpyFGMGwSCQSTrzSMKyGcOY.LMGZlaEvTITfAcAjYJCRaMJKNzbs(kbJePDCFUSnvotYGTBJJIXyGjgxpb , Boolean , Boolean )
   at zXltsuGhNYCMjfDKIQroIpHlWHNlA.OWPZBHPUyVtuFHgVsqAgtltQesPP(kveIcdZiuddJuYJCJVDulNKrYmgm , Exception , CancellationToken )
   --- End of inner exception stack trace ---
   at zXltsuGhNYCMjfDKIQroIpHlWHNlA.OWPZBHPUyVtuFHgVsqAgtltQesPP(kveIcdZiuddJuYJCJVDulNKrYmgm , Exception , CancellationToken )
   at yfslDotWsbJbzbZZnkxANhOpBrdD.KMphOdutOqirSNggVByTNFDlZZYs.DXoIZVqllaTshnKZZJdmUtcAOVnq(kveIcdZiuddJuYJCJVDulNKrYmgm )
   at qEcguUenSrzQYJFmHpQYSWqfAIPoA.LMGZlaEvTITfAcAjYJCRaMJKNzbs()
   at CShWJniZknOeEHUMQtqHiieVjTcG.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at ATrGRJBpHdUGsJRMWvBGgNRfwmSjA.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at uMStXuFjxUkHTWaSQAOuOJYOdwan.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   at yfslDotWsbJbzbZZnkxANhOpBrdD.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   --- End of inner exception stack trace ---
   at yfslDotWsbJbzbZZnkxANhOpBrdD.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   at uMStXuFjxUkHTWaSQAOuOJYOdwan.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at ATrGRJBpHdUGsJRMWvBGgNRfwmSjA.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at RMkDOjZXTbbkxvDNZcgpljkkChSaA.OWPZBHPUyVtuFHgVsqAgtltQesPP(kveIcdZiuddJuYJCJVDulNKrYmgm , Exception , CancellationToken )
21:40:54 http        [x] Exception was thrown when accessing https://nhentai.net/g/466168/: System.Net.WebException: The challenge solver threw an exception. ---> System.Net.WebException: The challenge solver threw an exception. ---> TeRDIggEPVtUxEYNZXRKlAWipSbEA: Failed to connect to FlareSolverr. Make sure that FlareSolverr is running on port 8191. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8191
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at NfiBUnEqtckatHAlrMRgwRdowkZIA.Gsemac.Net.IWebClient.UploadString(Uri address, String data)
   at fcYiqTpyFGMGwSCQSTrzSMKyGcOY.LMGZlaEvTITfAcAjYJCRaMJKNzbs(kbJePDCFUSnvotYGTBJJIXyGjgxpb , Boolean , Boolean )
   at zXltsuGhNYCMjfDKIQroIpHlWHNlA.OWPZBHPUyVtuFHgVsqAgtltQesPP(kveIcdZiuddJuYJCJVDulNKrYmgm , Exception , CancellationToken )
   --- End of inner exception stack trace ---
   at zXltsuGhNYCMjfDKIQroIpHlWHNlA.OWPZBHPUyVtuFHgVsqAgtltQesPP(kveIcdZiuddJuYJCJVDulNKrYmgm , Exception , CancellationToken )
   at yfslDotWsbJbzbZZnkxANhOpBrdD.KMphOdutOqirSNggVByTNFDlZZYs.DXoIZVqllaTshnKZZJdmUtcAOVnq(kveIcdZiuddJuYJCJVDulNKrYmgm )
   at qEcguUenSrzQYJFmHpQYSWqfAIPoA.LMGZlaEvTITfAcAjYJCRaMJKNzbs()
   at CShWJniZknOeEHUMQtqHiieVjTcG.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at ATrGRJBpHdUGsJRMWvBGgNRfwmSjA.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at uMStXuFjxUkHTWaSQAOuOJYOdwan.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   at yfslDotWsbJbzbZZnkxANhOpBrdD.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   --- End of inner exception stack trace ---
   at yfslDotWsbJbzbZZnkxANhOpBrdD.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   at uMStXuFjxUkHTWaSQAOuOJYOdwan.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at ATrGRJBpHdUGsJRMWvBGgNRfwmSjA.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at RMkDOjZXTbbkxvDNZcgpljkkChSaA.OWPZBHPUyVtuFHgVsqAgtltQesPP(kveIcdZiuddJuYJCJVDulNKrYmgm , Exception , CancellationToken )
   at yfslDotWsbJbzbZZnkxANhOpBrdD.KMphOdutOqirSNggVByTNFDlZZYs.DXoIZVqllaTshnKZZJdmUtcAOVnq(kveIcdZiuddJuYJCJVDulNKrYmgm )
   at qEcguUenSrzQYJFmHpQYSWqfAIPoA.LMGZlaEvTITfAcAjYJCRaMJKNzbs()
   at CShWJniZknOeEHUMQtqHiieVjTcG.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at ATrGRJBpHdUGsJRMWvBGgNRfwmSjA.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at uMStXuFjxUkHTWaSQAOuOJYOdwan.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   at XJwOVJgsNzZvqrhUWbjfgmozNvZE.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   at uMStXuFjxUkHTWaSQAOuOJYOdwan.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at ATrGRJBpHdUGsJRMWvBGgNRfwmSjA.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at uMStXuFjxUkHTWaSQAOuOJYOdwan.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   at XBajcqgLaaaMgCaOkUUfYDXRcjZhA.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   at uMStXuFjxUkHTWaSQAOuOJYOdwan.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at ATrGRJBpHdUGsJRMWvBGgNRfwmSjA.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at XiZbdrvHrqzHlgvVdmRMzbcyXZbs.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at ATrGRJBpHdUGsJRMWvBGgNRfwmSjA.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at uMStXuFjxUkHTWaSQAOuOJYOdwan.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   at ZvrEHQcXQNapTxAQJziyjsjThOSC.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   at uMStXuFjxUkHTWaSQAOuOJYOdwan.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at ATrGRJBpHdUGsJRMWvBGgNRfwmSjA.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at uMStXuFjxUkHTWaSQAOuOJYOdwan.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   at qpWMKrpRlrOKKdfRJzWRrTPOnNjx.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   at uMStXuFjxUkHTWaSQAOuOJYOdwan.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at ATrGRJBpHdUGsJRMWvBGgNRfwmSjA.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at uMStXuFjxUkHTWaSQAOuOJYOdwan.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   at yfslDotWsbJbzbZZnkxANhOpBrdD.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   --- End of inner exception stack trace ---
   at yfslDotWsbJbzbZZnkxANhOpBrdD.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   at uMStXuFjxUkHTWaSQAOuOJYOdwan.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at ATrGRJBpHdUGsJRMWvBGgNRfwmSjA.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at uMStXuFjxUkHTWaSQAOuOJYOdwan.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   at PZZYEJlQHdtTYJVTXLYSVwrShwli.ETLuQfVfXmfylQnXifCFVGMGfwoR(kveIcdZiuddJuYJCJVDulNKrYmgm , CancellationToken )
   at uMStXuFjxUkHTWaSQAOuOJYOdwan.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at ATrGRJBpHdUGsJRMWvBGgNRfwmSjA.ETLuQfVfXmfylQnXifCFVGMGfwoR(WebRequest , CancellationToken )
   at vpmOgenkbInLUokZYYZwvrJIkfLl.FdrDOUhRoCtzYgYvOZPQlPEFNgOX(String , CookieContainer , String[] , String , DZnIvsXmizmlyyBpPRhGwVkcOojD , String[] )
21:40:54 info grabbe [i] Got info for https://nhentai.net/g/466168/ using nhentai module
21:40:54 queue       [!] Skipped https://nhentai.net/g/466168/ (Invalid response or missing/outdated module)

**Comment by HDoujinDownloader** [comment]
The error seems to be coming from FlareSolverr when it attempts to download and patch the Chrome driver (which it uses to automate Google Chrome to bypass Cloudflare). It's returning a 404 error, so maybe the download endpoint has changed.

Try downloading the latest version of FlareSolverr here: https://github.com/FlareSolverr/FlareSolverr/releases/download/v3.3.2/flaresolverr_windows_x64.zip

Plop that archive into HDoujin Downloader's "plugins" folder, and delete all versions of the FlareSolverr plugin. Hopefully that resolves it.

**Comment by tazibal** [comment]
It helped, thank you :)
