### ISSUE TITLE
App isn't compatible with FlareSolverr >= 3.3.15

### ISSUE THREAD

**Issue by ale5000-git** [HDoujinDownloader/HDoujinDownloader#292]
If I use FlareSolverr without your app it is working fine:

Bash:
```
curl -L -X POST 'http://localhost:8191/v1' \
-H 'Content-Type: application/json' \
--data-raw '{
  "cmd": "request.get",
  "url": "https://www3.yggtorrent.qa/",
  "maxTimeout": 60000
}'
```

Output:
```
2024-03-02 23:05:59 INFO     FlareSolverr 3.3.16
2024-03-02 23:05:59 INFO     Testing web browser installation...
2024-03-02 23:05:59 INFO     Platform: Windows-10-10.0.19045-SP0
2024-03-02 23:05:59 INFO     Chrome / Chromium path: C:\Users\MyUser\Documents\flaresolverr_windows_x64\flaresolverr\chrome\chrome.exe
2024-03-02 23:05:59 INFO     Chrome / Chromium major version: 123
2024-03-02 23:05:59 INFO     Launching web browser...
2024-03-02 23:06:08 INFO     FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
2024-03-02 23:06:08 INFO     Test successful!
2024-03-02 23:06:08 INFO     Serving on http://0.0.0.0:8191
2024-03-02 23:08:12 INFO     Incoming request => POST /v1 body: {'cmd': 'request.get', 'url': 'https://www3.yggtorrent.qa/', 'maxTimeout': 60000}
2024-03-02 23:08:15 INFO     Challenge detected. Selector found: #challenge-spinner
2024-03-02 23:08:49 INFO     Challenge solved!
2024-03-02 23:08:50 INFO     Response in 37.887 s
2024-03-02 23:08:50 INFO     127.0.0.1 POST http://localhost:8191/v1 200 OK
```

But when I use it from HDoujinDownloader it doesn't work (both 3.3.15 and 3.3.16):
```
23:09:42 hdoujin dow [i] CLR Version: 4.0.30319.42000
23:09:42 hdoujin dow [i] Framework Version: 4.8.9181.0
23:09:42 hdoujin dow [i] OS Version: Microsoft Windows NT 10.0.19045.0 (64-bit)
23:09:42 hdoujin dow [i] Locale: it-IT
23:09:42 hdoujin dow [i] Path: %USERPROFILE%\Documents\HDoujin Downloader\HDoujin.Downloader-win\HDoujin Downloader.exe
23:09:42 hdoujin dow [i] Working Directory: %USERPROFILE%\Documents\HDoujin Downloader\HDoujin.Downloader-win
23:09:42 hdoujin dow [i] Timestamp: 02/03/2024 23:09:42
23:09:42 hdoujin dow [i] Product Version: 2023.11.8
23:09:42 hdoujin dow [i] Available Security Protocols: SSL 3.0, TLS 1.0, TLS 1.1, TLS 1.2, TLS 1.3
23:09:42 hdoujin dow [i] Standalone: False
23:09:42 hdoujin dow [i] Repositories: MyModules, Official Lua Repository, Internal
23:09:42 hdoujin dow [i] Theme: Default
23:09:53 queue       [i] Attempting to enqueue https://www3.yggtorrent.qa/
23:09:54 hdoujinchal [i] Using FlareSolverrChallengeHandler
23:09:54 flaresolver [i] Checking for FlareSolverr updates
23:09:54 flaresolver [i] Checking latest FlareSolverr version
23:09:55 flaresolver [i] Latest FlareSolverr version is 3.3.16
23:09:55 flaresolver [i] FlareSolverr is up to date (3.3.16)
23:09:55 flaresolver [i] Starting FlareSolverr process
23:09:58 flaresolver [i] Starting FlareSolverr process
23:10:01 flaresolver [x] Traceback (most recent call last):
23:10:01 flaresolver [x]   File "flaresolverr.py", line 101, in <module>
23:10:01 flaresolver [x]   File "utils.py", line 38, in get_flaresolverr_version
23:10:01 flaresolver [x]   File "json\__init__.py", line 346, in loads
23:10:01 flaresolver [x]   File "json\decoder.py", line 340, in decode
23:10:01 flaresolver [x] json.decoder.JSONDecodeError: Extra data: line 8 column 1 (char 195)
23:10:01 flaresolver [x] [7428] Failed to execute script 'flaresolverr' due to unhandled exception!
23:10:01 flaresolver [x] Failed to start FlareSolverr process
23:10:06 hdoujinchal [x] System.Net.WebException: The challenge solver threw an exception. ---> bHtdYHSXWZyxNruiFFWUwGPDcxXU: Failed to connect to FlareSolverr. Make sure that FlareSolverr is running on port 8191. ---> System.Net.WebException: Impossibile effettuare la connessione al server remoto. ---> System.Net.Sockets.SocketException: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione 127.0.0.1:8191
   in System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   in System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Fine della traccia dello stack dell'eccezione interna ---
   in System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   in System.Net.WebClient.UploadString(Uri address, String method, String data)
   in ncYZICyKyuRLBnGEvAPshwiPULlV.Gsemac.Net.IWebClient.UploadString(Uri address, String data)
   in FfykkcxwQEtvKhFnGHlroyTBnPgr.pKeHpJKTSWqYoJnYICNJOSArUTHj(YCjcZwiTFUAAMctvCDBZRpdaAPZeB , Boolean , Boolean )
   in RUJTeHEJCSupLkShMKnwDCYAGczCA.avpBTqZudVjTbHyygqCgPJmbZZbX(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , Exception , CancellationToken )
   --- Fine della traccia dello stack dell'eccezione interna ---
   in RUJTeHEJCSupLkShMKnwDCYAGczCA.avpBTqZudVjTbHyygqCgPJmbZZbX(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , Exception , CancellationToken )
   in QcEfCHnTZncHPMivreWClkXKgSVD.HhUOHeVNLRZJzrEZkagYcpGaIBTOA.dUOKHewLiyFBNIXgZEjggpfzfyRZ(YWGCbKLHfnWZWrNjNPdwVRLCdOAf )
   in MGOfglnvFxBludsXZDIADqdfQppTB.pKeHpJKTSWqYoJnYICNJOSArUTHj()
   in cVVENEwabpetqyctGblLEIbmrEQBA.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in ovHfXsGtKxRhQPudKpFIWdGScZwDb.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in MJguPNTXyUMVnxunIPUgyHVpRZWq.aVxgKKLSXgEjJpBmezBDvcFtERQV(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , CancellationToken )
   in QcEfCHnTZncHPMivreWClkXKgSVD.aVxgKKLSXgEjJpBmezBDvcFtERQV(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , CancellationToken )
   --- Fine della traccia dello stack dell'eccezione interna ---
   in QcEfCHnTZncHPMivreWClkXKgSVD.aVxgKKLSXgEjJpBmezBDvcFtERQV(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , CancellationToken )
   in MJguPNTXyUMVnxunIPUgyHVpRZWq.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in ovHfXsGtKxRhQPudKpFIWdGScZwDb.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in nOKVFAHcQfiSFKoiLYabZzfDqKcP.avpBTqZudVjTbHyygqCgPJmbZZbX(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , Exception , CancellationToken )
23:10:06 http        [x] Exception was thrown when accessing https://www3.yggtorrent.qa/: System.Net.WebException: The challenge solver threw an exception. ---> System.Net.WebException: The challenge solver threw an exception. ---> bHtdYHSXWZyxNruiFFWUwGPDcxXU: Failed to connect to FlareSolverr. Make sure that FlareSolverr is running on port 8191. ---> System.Net.WebException: Impossibile effettuare la connessione al server remoto. ---> System.Net.Sockets.SocketException: Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione 127.0.0.1:8191
   in System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   in System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Fine della traccia dello stack dell'eccezione interna ---
   in System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   in System.Net.WebClient.UploadString(Uri address, String method, String data)
   in ncYZICyKyuRLBnGEvAPshwiPULlV.Gsemac.Net.IWebClient.UploadString(Uri address, String data)
   in FfykkcxwQEtvKhFnGHlroyTBnPgr.pKeHpJKTSWqYoJnYICNJOSArUTHj(YCjcZwiTFUAAMctvCDBZRpdaAPZeB , Boolean , Boolean )
   in RUJTeHEJCSupLkShMKnwDCYAGczCA.avpBTqZudVjTbHyygqCgPJmbZZbX(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , Exception , CancellationToken )
   --- Fine della traccia dello stack dell'eccezione interna ---
   in RUJTeHEJCSupLkShMKnwDCYAGczCA.avpBTqZudVjTbHyygqCgPJmbZZbX(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , Exception , CancellationToken )
   in QcEfCHnTZncHPMivreWClkXKgSVD.HhUOHeVNLRZJzrEZkagYcpGaIBTOA.dUOKHewLiyFBNIXgZEjggpfzfyRZ(YWGCbKLHfnWZWrNjNPdwVRLCdOAf )
   in MGOfglnvFxBludsXZDIADqdfQppTB.pKeHpJKTSWqYoJnYICNJOSArUTHj()
   in cVVENEwabpetqyctGblLEIbmrEQBA.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in ovHfXsGtKxRhQPudKpFIWdGScZwDb.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in MJguPNTXyUMVnxunIPUgyHVpRZWq.aVxgKKLSXgEjJpBmezBDvcFtERQV(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , CancellationToken )
   in QcEfCHnTZncHPMivreWClkXKgSVD.aVxgKKLSXgEjJpBmezBDvcFtERQV(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , CancellationToken )
   --- Fine della traccia dello stack dell'eccezione interna ---
   in QcEfCHnTZncHPMivreWClkXKgSVD.aVxgKKLSXgEjJpBmezBDvcFtERQV(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , CancellationToken )
   in MJguPNTXyUMVnxunIPUgyHVpRZWq.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in ovHfXsGtKxRhQPudKpFIWdGScZwDb.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in nOKVFAHcQfiSFKoiLYabZzfDqKcP.avpBTqZudVjTbHyygqCgPJmbZZbX(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , Exception , CancellationToken )
   in QcEfCHnTZncHPMivreWClkXKgSVD.HhUOHeVNLRZJzrEZkagYcpGaIBTOA.dUOKHewLiyFBNIXgZEjggpfzfyRZ(YWGCbKLHfnWZWrNjNPdwVRLCdOAf )
   in MGOfglnvFxBludsXZDIADqdfQppTB.pKeHpJKTSWqYoJnYICNJOSArUTHj()
   in cVVENEwabpetqyctGblLEIbmrEQBA.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in ovHfXsGtKxRhQPudKpFIWdGScZwDb.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in MJguPNTXyUMVnxunIPUgyHVpRZWq.aVxgKKLSXgEjJpBmezBDvcFtERQV(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , CancellationToken )
   in xMKWzciVAjioASShObhzWFbCGwvt.aVxgKKLSXgEjJpBmezBDvcFtERQV(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , CancellationToken )
   in MJguPNTXyUMVnxunIPUgyHVpRZWq.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in ovHfXsGtKxRhQPudKpFIWdGScZwDb.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in MJguPNTXyUMVnxunIPUgyHVpRZWq.aVxgKKLSXgEjJpBmezBDvcFtERQV(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , CancellationToken )
   in xEKKmBgLveltIrGdwGMjDsGeMKjJA.aVxgKKLSXgEjJpBmezBDvcFtERQV(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , CancellationToken )
   in MJguPNTXyUMVnxunIPUgyHVpRZWq.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in ovHfXsGtKxRhQPudKpFIWdGScZwDb.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in bGzdpEnXcygtLDccpcLMDlfLVsXv.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in ovHfXsGtKxRhQPudKpFIWdGScZwDb.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in MJguPNTXyUMVnxunIPUgyHVpRZWq.aVxgKKLSXgEjJpBmezBDvcFtERQV(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , CancellationToken )
   in rsHArvyWwDJzEEpYHpeHXzFgIdwe.aVxgKKLSXgEjJpBmezBDvcFtERQV(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , CancellationToken )
   in MJguPNTXyUMVnxunIPUgyHVpRZWq.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in ovHfXsGtKxRhQPudKpFIWdGScZwDb.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in MJguPNTXyUMVnxunIPUgyHVpRZWq.aVxgKKLSXgEjJpBmezBDvcFtERQV(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , CancellationToken )
   in QswKEGpRwpbfoMAcNpQHNqYvukDv.aVxgKKLSXgEjJpBmezBDvcFtERQV(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , CancellationToken )
   in MJguPNTXyUMVnxunIPUgyHVpRZWq.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in ovHfXsGtKxRhQPudKpFIWdGScZwDb.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in MJguPNTXyUMVnxunIPUgyHVpRZWq.aVxgKKLSXgEjJpBmezBDvcFtERQV(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , CancellationToken )
   in QcEfCHnTZncHPMivreWClkXKgSVD.aVxgKKLSXgEjJpBmezBDvcFtERQV(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , CancellationToken )
   --- Fine della traccia dello stack dell'eccezione interna ---
   in QcEfCHnTZncHPMivreWClkXKgSVD.aVxgKKLSXgEjJpBmezBDvcFtERQV(YWGCbKLHfnWZWrNjNPdwVRLCdOAf , CancellationToken )
   in MJguPNTXyUMVnxunIPUgyHVpRZWq.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in ovHfXsGtKxRhQPudKpFIWdGScZwDb.aVxgKKLSXgEjJpBmezBDvcFtERQV(WebRequest , CancellationToken )
   in DSCCXNrygCUWaTohEATyFAYtJhRc.rbTdIxdVdUSEmQjWAsRYsJXmmHsfb(String , CookieContainer , String[] , String , nUGbnyiNZNEbTRpsbUVJDtDqHIkxA , String[] , Boolean )
23:10:06 queue       [!] Skipped https://www3.yggtorrent.qa/ (Invalid response or missing/outdated module)
```

**PS:** The url is only an example, it is broken also with other urls.

**Comment by HDoujinDownloader** [comment]
Oddly, it appears the error is coming from FlareSolverr itself when it tries to read its version information:
```
23:10:01 flaresolver [x] Traceback (most recent call last):
23:10:01 flaresolver [x]   File "flaresolverr.py", line 101, in <module>
23:10:01 flaresolver [x]   File "utils.py", line 38, in get_flaresolverr_version
23:10:01 flaresolver [x]   File "json\__init__.py", line 346, in loads
23:10:01 flaresolver [x]   File "json\decoder.py", line 340, in decode
23:10:01 flaresolver [x] json.decoder.JSONDecodeError: Extra data: line 8 column 1 (char 195)
23:10:01 flaresolver [x] [7428] Failed to execute script 'flaresolverr' due to unhandled exception!
```
It's encountering an invalid `Ã` character at the end of its `package.json` file. This is probably an encoding issue, but I'm not sure why it happens when it's launched from HDoujin.

Try deleting everything that's already inside of the "plugins" folder. Then plop the [FlareSolverr ZIP archive](https://github.com/FlareSolverr/FlareSolverr/releases/latest/download/flaresolverr_windows_x64.zip) directly inside without extracting it (let HDoujin extract the archive itself).

Let me know if the problem still occurs after that. I haven't been able to reproduce this issue personally.

**Comment by ale5000-git** [comment]
Thanks,
now it works but it is very strange, I was getting the error on multiple PC before.
Maybe I was getting a corrupted zip from GitHub with the flaresolverr auto update.
