### ISSUE TITLE
nhentai + flaresolverr doesn't work

### ISSUE THREAD

**Issue by Romangelo** [HDoujinDownloader/HDoujinDownloader#301]
`17:34:50 queue       [i] Attempting to enqueue https://nhentai.net/g/253692/
17:34:50 hdoujinchal [i] Using FlareSolverrChallengeHandler
17:34:50 flaresolver [i] Starting FlareSolverr process
17:34:50 flaresolver [i] Starting FlareSolverr process
17:34:50 flaresolver [i] FlareSolverr 3.3.16
17:34:50 flaresolver [i] Testing web browser installation...
17:34:50 flaresolver [i] Platform: Windows-10-10.0.19045-SP0
17:34:50 flaresolver [i] Chrome / Chromium path: Z:\X\H-Doujin\HDD\plugins\flaresolverr_windows_x64\flaresolverr\chrome\chrome.exe
17:34:50 flaresolver [i] Chrome / Chromium major version: 123
17:34:50 flaresolver [i] Launching web browser...
17:34:50 flaresolver [i] FlareSolverr User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
17:34:50 flaresolver [i] Test successful!
17:34:50 flaresolver [i] Serving on http://0.0.0.0:8191
17:34:50 flaresolver [i] FlareSolverr is now listening on port 8191
17:34:50 flaresolver [i] Creating a new session
17:34:50 flaresolver [i] Incoming request => POST /v1 body: {'cmd': 'sessions.create', 'download': False, 'maxTimeout': 60000, 'headers': {}, 'cookies': [], 'returnOnlyCookies': False}
17:34:50 flaresolver [!] Request parameter 'headers' was removed in FlareSolverr v2.
17:34:50 flaresolver [i] Response in 0.59 s
17:34:50 flaresolver [i] 127.0.0.1 POST http://localhost:8191/v1 200 OK
17:34:50 flaresolver [i] Created session with ID 112b9851-ea2e-11ee-9137-e848b8c82000
17:34:50 flaresolver [i] Incoming request => POST /v1 body: {'cmd': 'request.get', 'download': True, 'url': 'https://nhentai.net/g/253692/', 'maxTimeout': 100000, 'headers': {'Accept-Language': 'en-US,en;q=0.9', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'Keep-Alive'}, 'cookies': [], 'session': '112b9851-ea2e-11ee-9137-e848b8c82000', 'returnOnlyCookies': False}
17:34:50 flaresolver [!] Request parameter 'headers' was removed in FlareSolverr v2.
17:34:50 flaresolver [!] Request parameter 'download' was removed in FlareSolverr v2.
17:34:50 flaresolver [i] Challenge detected. Title found: Just a moment...
17:34:50 hdoujinchal [x] System.Net.WebException: The challenge solver threw an exception. ---> _HNIxJzcgPvE5k65NdNWmcpZvrii: Failed to execute FlareSolverr command. ---> System.Net.WebException: The request was aborted: The operation has timed out.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at _L7exFvAEJSsXMrbuUSewMFJXm9h.Gsemac.Net.IWebClient.UploadString(Uri address, String data)
   at _saSBDT7phoX5UzLF7snel0NHkJd._GnLAvplI0fCMiQ2a3UBtZpxGK88(_sI9aIHzlIh4VucAPmYKdsSGM7ii , Boolean , Boolean )
   at _tMl7A4anieFQaiYNSujINqVbg7R._Xj3dmKs3MobsnnWpF9uRbHrJyKg(_gInp3i039JzZn0BZaFqaCwNmc2p , Exception , CancellationToken )
   --- End of inner exception stack trace ---
   at _tMl7A4anieFQaiYNSujINqVbg7R._Xj3dmKs3MobsnnWpF9uRbHrJyKg(_gInp3i039JzZn0BZaFqaCwNmc2p , Exception , CancellationToken )
   at _dy2JnpArY3M7MKWBl2ScjBXyuoo._ANs4WJEm9wuqueEMBrzcpLzTeuK._5s8iKQVNOteRD7DHllz4n1tlVkc(_gInp3i039JzZn0BZaFqaCwNmc2p )
   at _sEdD1D1koKWiOkzOMVUcdGSn0LD._GnLAvplI0fCMiQ2a3UBtZpxGK88()
   at _7wi2UuL50HMca8GsXlZoEZyKIrz._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _5OjwSSSjnSFKQrF5eLV4MsLHaQF._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _gFScAarB8avdYcJIaUxAes8hSpq._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   at _dy2JnpArY3M7MKWBl2ScjBXyuoo._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   --- End of inner exception stack trace ---
   at _dy2JnpArY3M7MKWBl2ScjBXyuoo._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   at _gFScAarB8avdYcJIaUxAes8hSpq._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _5OjwSSSjnSFKQrF5eLV4MsLHaQF._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _RTbvzqczvLpA2T5K7ryBk7T9w7g._Xj3dmKs3MobsnnWpF9uRbHrJyKg(_gInp3i039JzZn0BZaFqaCwNmc2p , Exception , CancellationToken )
17:34:50 http        [x] Exception was thrown when accessing https://nhentai.net/g/253692/: System.Net.WebException: The challenge solver threw an exception. ---> System.Net.WebException: The challenge solver threw an exception. ---> _HNIxJzcgPvE5k65NdNWmcpZvrii: Failed to execute FlareSolverr command. ---> System.Net.WebException: The request was aborted: The operation has timed out.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at _L7exFvAEJSsXMrbuUSewMFJXm9h.Gsemac.Net.IWebClient.UploadString(Uri address, String data)
   at _saSBDT7phoX5UzLF7snel0NHkJd._GnLAvplI0fCMiQ2a3UBtZpxGK88(_sI9aIHzlIh4VucAPmYKdsSGM7ii , Boolean , Boolean )
   at _tMl7A4anieFQaiYNSujINqVbg7R._Xj3dmKs3MobsnnWpF9uRbHrJyKg(_gInp3i039JzZn0BZaFqaCwNmc2p , Exception , CancellationToken )
   --- End of inner exception stack trace ---
   at _tMl7A4anieFQaiYNSujINqVbg7R._Xj3dmKs3MobsnnWpF9uRbHrJyKg(_gInp3i039JzZn0BZaFqaCwNmc2p , Exception , CancellationToken )
   at _dy2JnpArY3M7MKWBl2ScjBXyuoo._ANs4WJEm9wuqueEMBrzcpLzTeuK._5s8iKQVNOteRD7DHllz4n1tlVkc(_gInp3i039JzZn0BZaFqaCwNmc2p )
   at _sEdD1D1koKWiOkzOMVUcdGSn0LD._GnLAvplI0fCMiQ2a3UBtZpxGK88()
   at _7wi2UuL50HMca8GsXlZoEZyKIrz._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _5OjwSSSjnSFKQrF5eLV4MsLHaQF._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _gFScAarB8avdYcJIaUxAes8hSpq._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   at _dy2JnpArY3M7MKWBl2ScjBXyuoo._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   --- End of inner exception stack trace ---
   at _dy2JnpArY3M7MKWBl2ScjBXyuoo._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   at _gFScAarB8avdYcJIaUxAes8hSpq._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _5OjwSSSjnSFKQrF5eLV4MsLHaQF._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _RTbvzqczvLpA2T5K7ryBk7T9w7g._Xj3dmKs3MobsnnWpF9uRbHrJyKg(_gInp3i039JzZn0BZaFqaCwNmc2p , Exception , CancellationToken )
   at _dy2JnpArY3M7MKWBl2ScjBXyuoo._ANs4WJEm9wuqueEMBrzcpLzTeuK._5s8iKQVNOteRD7DHllz4n1tlVkc(_gInp3i039JzZn0BZaFqaCwNmc2p )
   at _sEdD1D1koKWiOkzOMVUcdGSn0LD._GnLAvplI0fCMiQ2a3UBtZpxGK88()
   at _7wi2UuL50HMca8GsXlZoEZyKIrz._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _5OjwSSSjnSFKQrF5eLV4MsLHaQF._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _gFScAarB8avdYcJIaUxAes8hSpq._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   at _GGPdZTciGPhbleD2hK1X7i3Mozy._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   at _gFScAarB8avdYcJIaUxAes8hSpq._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _5OjwSSSjnSFKQrF5eLV4MsLHaQF._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _gFScAarB8avdYcJIaUxAes8hSpq._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   at _B9dAaVSomJRdOTIxHybsIZPQhBNA._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   at _gFScAarB8avdYcJIaUxAes8hSpq._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _5OjwSSSjnSFKQrF5eLV4MsLHaQF._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _gFScAarB8avdYcJIaUxAes8hSpq._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   at _KapAfnXNR9NZwkBhUVxpHk8AnKc._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   at _gFScAarB8avdYcJIaUxAes8hSpq._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _5OjwSSSjnSFKQrF5eLV4MsLHaQF._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _B1RD46KGNMQD9WAYnNBWI5Kegow._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _5OjwSSSjnSFKQrF5eLV4MsLHaQF._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _gFScAarB8avdYcJIaUxAes8hSpq._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   at _WcviqEWdfpvH4GPYNi6LA9oOXWL._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   at _gFScAarB8avdYcJIaUxAes8hSpq._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _5OjwSSSjnSFKQrF5eLV4MsLHaQF._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _gFScAarB8avdYcJIaUxAes8hSpq._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   at _f3LmeDBHSNSmM39HRcOLnyjcage._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   at _gFScAarB8avdYcJIaUxAes8hSpq._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _5OjwSSSjnSFKQrF5eLV4MsLHaQF._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _gFScAarB8avdYcJIaUxAes8hSpq._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   at _dy2JnpArY3M7MKWBl2ScjBXyuoo._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   --- End of inner exception stack trace ---
   at _dy2JnpArY3M7MKWBl2ScjBXyuoo._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   at _gFScAarB8avdYcJIaUxAes8hSpq._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _5OjwSSSjnSFKQrF5eLV4MsLHaQF._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _gFScAarB8avdYcJIaUxAes8hSpq._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   at _7YYgcCAveF3gBs5FPR12aUz5JxL._J2SFTxrfnPgNPn1uab9BduckJdw(_gInp3i039JzZn0BZaFqaCwNmc2p , CancellationToken )
   at _gFScAarB8avdYcJIaUxAes8hSpq._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _5OjwSSSjnSFKQrF5eLV4MsLHaQF._J2SFTxrfnPgNPn1uab9BduckJdw(WebRequest , CancellationToken )
   at _zDmd9m5U5jm6pKMKxWhKJrsOLYg._DKinJCb3IkluPlvDY7CMWbkAHQI(String , CookieContainer , String[] , String , _3mxju3erVwkSsl9md5bQZHF2WRb , String[] , Boolean )
17:34:50 flaresolver [x] Error: Error solving the challenge. Timeout after 100.0 seconds.
17:34:50 flaresolver [i] Response in 100.115 s
17:34:50 flaresolver [i] 127.0.0.1 POST http://localhost:8191/v1 500 Internal Server Error
17:34:50 info grabbe [i] Got info for https://nhentai.net/g/253692/ (nhentai)
17:34:50 queue       [!] Skipped https://nhentai.net/g/253692/ (Invalid response or missing/outdated module)`

**Comment by HDoujinDownloader** [comment]
It's not nhentai-specific, but seems to be an issue with FlareSolverr. I've reproduced the problem on my end, and it appears to be happening for others as well: FlareSolverr/FlareSolverr#1036

We'll have to wait for the FlareSolverr team to issue a fix.
