### ISSUE TITLE
[LezhinUS] Error when downloading 2 specific chapters

### ISSUE THREAD

**Issue by ShadowHunter232** [HDoujinDownloader/HDoujinDownloader#304]
When trying to download 2 chapters of a webtoon on Lezhin I'm getting this error message:
```
18:55:23 http        [!] System.ArgumentException: Specified value has invalid Control characters.
Parameter name: value
   at System.Net.WebHeaderCollection.CheckBadChars(String name, Boolean isHeaderValue)
   at System.Net.HttpWebRequest.SetSpecialHeaders(String HeaderName, String value)
   at _lrNIBf6QwOzI6asedHedTIaKd4G._xgh1sCyQBQrUnHiizlMyxuUsbve(String )
   at _6YbnFWgAADr92rulgASFJ9mHTJAA._ps7zgvUImaxRM7vNlHv76rON5Eh(String , CookieContainer , String[] , String , _A0oU1jAym9YBNXpFVXllJXlXeID , String[] , Boolean )
18:55:23 page grabbe [x] System.ArgumentException: Specified value has invalid Control characters.
Parameter name: value
   at _q9r6nRJwen9YnurnWpXCHjAB3gC._vt775j1qa9beSMmCaXXKwoW0PwC(IEnumerable`1 , _XeMwTipI9eKUadrfL1vmo2Nc7yP , _lVKipORwtAx8v9LaNaTr6FYzFEB )
   at _qYJayOJOS1m9HoHULYr2rZaSfeG._FIXsbjNihh0eL3fEyTbcJL4v8bsA(String& )
18:55:23 login       [i] User is currently logged in
18:55:23 http        [!] System.ArgumentException: Specified value has invalid Control characters.
Parameter name: value
   at System.Net.WebHeaderCollection.CheckBadChars(String name, Boolean isHeaderValue)
   at System.Net.HttpWebRequest.SetSpecialHeaders(String HeaderName, String value)
   at _lrNIBf6QwOzI6asedHedTIaKd4G._xgh1sCyQBQrUnHiizlMyxuUsbve(String )
   at _6YbnFWgAADr92rulgASFJ9mHTJAA._ps7zgvUImaxRM7vNlHv76rON5Eh(String , CookieContainer , String[] , String , _A0oU1jAym9YBNXpFVXllJXlXeID , String[] , Boolean )
18:55:23 page grabbe [x] System.ArgumentException: Specified value has invalid Control characters.
Parameter name: value
   at _q9r6nRJwen9YnurnWpXCHjAB3gC._vt775j1qa9beSMmCaXXKwoW0PwC(IEnumerable`1 , _XeMwTipI9eKUadrfL1vmo2Nc7yP , _lVKipORwtAx8v9LaNaTr6FYzFEB )
   at _qYJayOJOS1m9HoHULYr2rZaSfeG._FIXsbjNihh0eL3fEyTbcJL4v8bsA(String& )
```

I'm thinking it maybe has to do something with the URL:
https://www.lezhinus.com/en/comic/my_jooin/%08x2

The other URL looks the same as this one. And chapters without the "%" in front of it download just fine.

**Comment by DionCali** [comment]
Got another error when downloading a chapter this time without the % in the url:
```
14:37:46 http        [!] System.ArgumentException: Specified value has invalid Control characters.
Parameter name: value
   at System.Net.WebHeaderCollection.CheckBadChars(String name, Boolean isHeaderValue)
   at System.Net.HttpWebRequest.SetSpecialHeaders(String HeaderName, String value)
   at _lrNIBf6QwOzI6asedHedTIaKd4G._xgh1sCyQBQrUnHiizlMyxuUsbve(String )
   at _6YbnFWgAADr92rulgASFJ9mHTJAA._ps7zgvUImaxRM7vNlHv76rON5Eh(String , CookieContainer , String[] , String , _A0oU1jAym9YBNXpFVXllJXlXeID , String[] , Boolean )
14:37:46 page grabbe [x] System.ArgumentException: Specified value has invalid Control characters.
Parameter name: value
   at _q9r6nRJwen9YnurnWpXCHjAB3gC._vt775j1qa9beSMmCaXXKwoW0PwC(IEnumerable`1 , _XeMwTipI9eKUadrfL1vmo2Nc7yP , _lVKipORwtAx8v9LaNaTr6FYzFEB )
   at _qYJayOJOS1m9HoHULYr2rZaSfeG._FIXsbjNihh0eL3fEyTbcJL4v8bsA(String& )
14:37:46 hdoujin dow [x] An error occurred while moving : System.NullReferenceException: Object reference not set to an instance of an object.
   at _hGrpq66r4DRBmLpAkZaXHh9IZlaA.⁮‮‏⁫⁪⁭⁫‍‏⁫‍‮​⁬⁮⁮‏‎⁬‍‭⁮​⁪‏‌‪‍‮⁮‬⁪​⁫⁭⁪‭‫⁪⁭‮(String )
   at _hGrpq66r4DRBmLpAkZaXHh9IZlaA._Plx9qg5u6BBc0p34ESvjIzrp7r5(_GLIRyvyZRR15H8wXyYpZNsbPGyA )
```

**Comment by HDoujinDownloader** [comment]
@ShadowHunter232 Not yet, I apologize-- I'm so far unable to reproduce it. I wasn't able to test with the chapter you posted on account of it being a paid chapter, but I did test this one I found: https://www.lezhinus.com/en/comic/hooked_cooked/%08e1

It completed without any issues with the latest release. Do you have the same problem with this one?

**Comment by HDoujinDownloader** [comment]
It's failing while setting the `referer` header, which is likely a result of the `%` character as you noted. I'm not sure why though, because it sets it just fine and carries on when I run the download on my end. Either way, I'll add some error handling so that it continues the download even if it fails to set the header.

Could you show me the details from the top of the log too so I can see if there's anything about the environment you're running it in that might be related?

**Comment by HDoujinDownloader** [comment]
@ShadowHunter232 Yes! I made it so it so that it just ignores "bad" referrer values. I hadn't tested yet that it had solved this particular problem, but I'm glad it did. 👏👏
