### ISSUE TITLE
Pages not downloading

### ISSUE THREAD

**Issue by mrstan3772** [HDoujinDownloader/HDoujinDownloader#39]
**Version:** 2021.10.12.0
**Component**: FlareSolverr v2.0.2
**Platform**: Windows (not working on linux on wine due to CloudFlare DDoS protection and incompatibility i guess)
**URL**:  https://www.webtoon.xyz/
**Origin**: After an update to FlareSolverr v2.0.2 with v2021.10.12.0. I also encountered a lot of download errors showing the message "some failed" even though all the chapters / pages have been downloaded.
**Resolution**: FlareSolverr seem working perfectly on HDoujin Downloader 2021.5.15.0-rc2 and FlareSolverr v1.2.9, all page are saved.

I sended log with contact form on https://doujindownloader.com/contact/.

**Comment by mrstan3772** [comment]
Or all chapters are present but only watermark page is in folder.

**Comment by HDoujinDownloader** [comment]
FlareSolverr v2.0.0+ removed a few parameters that used to be present in previous versions. In particular, the `download` parameter is no longer available, making it no longer possible to download files through FlareSolverr. I just uploaded a [new release](https://github.com/HDoujinDownloader/HDoujinDownloader/releases/tag/v2021.10.12.0) that addresses some compatibility issues with this version of FlareSolverr, so it should work in most cases.

However, for this particular site, you'll have to use an earlier version of FlareSolverr with the `download` parameter intact. The last suitable release is [v1.2.9](https://github.com/FlareSolverr/FlareSolverr/releases/tag/v1.2.9). By deleting all versions of the plugin except for v1.2.9, downloads from this site should proceed normally with the latest release of HDoujin Downloader.

There is some discussion on the FlareSolverr project about restoring the `download` parameter for later versions (FlareSolverr/FlareSolverr#207), so hopefully it's restored eventually. 

> not working on linux on wine due to CloudFlare DDoS protection and incompatibility i guess

Thanks for letting me know about this, by the way. Since there is a build of FlareSolverr for Linux, it should work, theoretically, but I haven't tested it out personally yet. I'll look into it at some point.

**Comment by StormJumper** [comment]
So does this mean those using Windows should revert back to this version as well?

**Comment by HDoujinDownloader** [comment]
> So does this mean those using Windows should revert back to this version as well?

I would recommend it, yeah. FlareSolverr v1.2.9 might not work for IPs receiving more advanced challenges, but so long as it still works for you I would avoid updating the plugin for now.

**Comment by mrstan3772** [comment]
I can no longer download because the challenge resolution timeout is too long.

**Comment by HDoujinDownloader** [comment]
> I can no longer download because the challenge resolution timeout is too long.

What version of FlareSolverr are you using? What do you see in the log (Tools > Log Viewer) when you attempt to run the download?

**Comment by StormJumper** [comment]
I got different message from your other site? I was told to use 2.0.2?

**Comment by mrstan3772** [comment]
[1636643725-debug.log](https://github.com/HDoujinDownloader/HDoujinDownloader/files/7521466/1636643725-debug.log)

FlareSolverr-v1.2.9-windows-x64 & HDoujin-v2021.11.8

### _**LOG VIEWER**_

`16:32:52 hdoujinchal [x] System.Net.WebException: The challenge solver threw an exception. ---> WPIDfmbHuAQKCWiPltpFgpSpwpCJA: Failed to execute FlareSolverr command. ---> System.Net.WebException: Le délai d'attente de l'opération a expiré.
   à System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   à System.Net.WebClient.UploadString(Uri address, String method, String data)
   à KtjZzlfYAnjwWydnFFffachjpPsDA.Gsemac.Net.IWebClient.UploadString(Uri address, String data)
   à grZgXPmNoBKUFmOWubLwtOMzcBpr.HSpXQfyDHfwJGwSAtBkajdmtLwBp(njQecPhKbZzlNGiQnnlQakcetHSVA , Boolean )
   à qmstDePmaBeGUllQkyJrQLLshgmR.DpMakDBKTMJakAlNAIefHKziZVmKb(fBoJVvvlbTmoKsLHCdnXasIROPnb , CancellationToken )
   --- Fin de la trace de la pile d'exception interne ---
   à qmstDePmaBeGUllQkyJrQLLshgmR.DpMakDBKTMJakAlNAIefHKziZVmKb(fBoJVvvlbTmoKsLHCdnXasIROPnb , CancellationToken )
   à twdSwcgpioBcSVPiZSZHkdqmavWd.MqNejqsxbyHGpDvtfIqpEWYEyviW.QEPmmmDSkPDmzECjcsxUBCTTUWCi()
   à LiydIthzHqWzttqOyVsYDRaIWkJL.ViSFOvYduvnhAkHuENbYsfMJRtTf(WebRequest , CancellationToken )
   à DBgjeRgkyshORfhCckdXZyBqFRneA.ViSFOvYduvnhAkHuENbYsfMJRtTf(WebRequest , CancellationToken )
   à qFhsxwJidjweWjqNJyhaMXlxObIy.ViSFOvYduvnhAkHuENbYsfMJRtTf(fBoJVvvlbTmoKsLHCdnXasIROPnb , CancellationToken )
   à twdSwcgpioBcSVPiZSZHkdqmavWd.ViSFOvYduvnhAkHuENbYsfMJRtTf(fBoJVvvlbTmoKsLHCdnXasIROPnb , CancellationToken )
   --- Fin de la trace de la pile d'exception interne ---
   à twdSwcgpioBcSVPiZSZHkdqmavWd.ViSFOvYduvnhAkHuENbYsfMJRtTf(fBoJVvvlbTmoKsLHCdnXasIROPnb , CancellationToken )
   à qFhsxwJidjweWjqNJyhaMXlxObIy.ViSFOvYduvnhAkHuENbYsfMJRtTf(WebRequest , CancellationToken )
   à DBgjeRgkyshORfhCckdXZyBqFRneA.ViSFOvYduvnhAkHuENbYsfMJRtTf(WebRequest , CancellationToken )
   à cjDORBuzStlkzcQIofpCTDGCFIIjA.ViSFOvYduvnhAkHuENbYsfMJRtTf(WebRequest , CancellationToken )
   à EetmqxSykufkOHERrWeiSbibIWvl.ViSFOvYduvnhAkHuENbYsfMJRtTf(fBoJVvvlbTmoKsLHCdnXasIROPnb , CancellationToken )
16:32:52 http        [x] Exception was thrown when accessing https://www.webtoon.xyz/read/3cm-hunter/: System.Net.WebException: The challenge solver threw an exception. ---> WPIDfmbHuAQKCWiPltpFgpSpwpCJA: Failed to execute FlareSolverr command. ---> System.Net.WebException: Le délai d'attente de l'opération a expiré.
   à System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   à System.Net.WebClient.UploadString(Uri address, String method, String data)
   à KtjZzlfYAnjwWydnFFffachjpPsDA.Gsemac.Net.IWebClient.UploadString(Uri address, String data)
   à grZgXPmNoBKUFmOWubLwtOMzcBpr.HSpXQfyDHfwJGwSAtBkajdmtLwBp(njQecPhKbZzlNGiQnnlQakcetHSVA , Boolean )
   à qmstDePmaBeGUllQkyJrQLLshgmR.DpMakDBKTMJakAlNAIefHKziZVmKb(fBoJVvvlbTmoKsLHCdnXasIROPnb , CancellationToken )
   --- Fin de la trace de la pile d'exception interne ---
   à qmstDePmaBeGUllQkyJrQLLshgmR.DpMakDBKTMJakAlNAIefHKziZVmKb(fBoJVvvlbTmoKsLHCdnXasIROPnb , CancellationToken )
   à twdSwcgpioBcSVPiZSZHkdqmavWd.MqNejqsxbyHGpDvtfIqpEWYEyviW.QEPmmmDSkPDmzECjcsxUBCTTUWCi()
   à LiydIthzHqWzttqOyVsYDRaIWkJL.ViSFOvYduvnhAkHuENbYsfMJRtTf(WebRequest , CancellationToken )
   à DBgjeRgkyshORfhCckdXZyBqFRneA.ViSFOvYduvnhAkHuENbYsfMJRtTf(WebRequest , CancellationToken )
   à qFhsxwJidjweWjqNJyhaMXlxObIy.ViSFOvYduvnhAkHuENbYsfMJRtTf(fBoJVvvlbTmoKsLHCdnXasIROPnb , CancellationToken )
   à twdSwcgpioBcSVPiZSZHkdqmavWd.ViSFOvYduvnhAkHuENbYsfMJRtTf(fBoJVvvlbTmoKsLHCdnXasIROPnb , CancellationToken )
   --- Fin de la trace de la pile d'exception interne ---
   à twdSwcgpioBcSVPiZSZHkdqmavWd.ViSFOvYduvnhAkHuENbYsfMJRtTf(fBoJVvvlbTmoKsLHCdnXasIROPnb , CancellationToken )
   à qFhsxwJidjweWjqNJyhaMXlxObIy.ViSFOvYduvnhAkHuENbYsfMJRtTf(WebRequest , CancellationToken )
   à DBgjeRgkyshORfhCckdXZyBqFRneA.ViSFOvYduvnhAkHuENbYsfMJRtTf(WebRequest , CancellationToken )
   à cjDORBuzStlkzcQIofpCTDGCFIIjA.ViSFOvYduvnhAkHuENbYsfMJRtTf(WebRequest , CancellationToken )
   à EetmqxSykufkOHERrWeiSbibIWvl.ViSFOvYduvnhAkHuENbYsfMJRtTf(fBoJVvvlbTmoKsLHCdnXasIROPnb , CancellationToken )
   à qFhsxwJidjweWjqNJyhaMXlxObIy.ViSFOvYduvnhAkHuENbYsfMJRtTf(WebRequest , CancellationToken )
   à DBgjeRgkyshORfhCckdXZyBqFRneA.ViSFOvYduvnhAkHuENbYsfMJRtTf(WebRequest , CancellationToken )
   à kzlzHskJQPzFpEmDoikhGUDLLlsI.OmiDvYQVPBzpxuTtgTxNSDASVLdt(String , CookieContainer , String[] , String , ctPRPchyQLaFIAzbqfSmnIrTYAuW , String[] )
16:32:52 hdoujinchal [i] Using FlareSolverr IUAM Challenge Solver
16:32:52 flaresolver [x] 2021-11-11T16:31:27+01:00 ERROR REQ-4 Error: Maximum timeout reached. maxTimeout=100000 (ms)
16:32:52 flaresolver [x]     at C:\snapshot\FlareSolverr\node_modules\await-timeout\src\utils.js:20:38
16:32:52 flaresolver [x]     at Timeout.<anonymous> (C:\snapshot\FlareSolverr\node_modules\await-timeout\src\index.js:32:46)
16:32:52 flaresolver [x]     at listOnTimeout (internal/timers.js:549:17)
16:32:52 flaresolver [x]     at processTimers (internal/timers.js:492:7)
16:32:52 flaresolver [x] 2021-11-11T16:31:27+01:00 ERROR REQ-4 Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=100000 (ms)
16:33:59 queue       [!] Skipped https://www.webtoon.xyz/read/3cm-hunter/ (Invalid response or missing/outdated module)
`

**Comment by mrstan3772** [comment]
It's seem working with FlareSolverr-v2.0.2 and lastestr HDoujin version.

**Comment by mrstan3772** [comment]
DDoS protection page notification appear with FlareSolverr v1.2.9 so i use my script with puppeteer but each page is protected with cloudflare (cross domain protection) on this website. I cannot use puppeteer with headless mode and forced to scroll all content before downloading (some lazy load). The plugin puppeteer-extra-plugin-stealth change anything. 
It takes longer for each chapter to download.

**Comment by mrstan3772** [comment]
Same error with FlareSolverr 2.0.2 after some url bookmarks checked. DDoS protection notification.

**Comment by mrstan3772** [comment]
After several attempts I succeeded but the first attempts to resolve the challenge fail before they succeed on FlareSolverr v1.2.9.

**Comment by StormJumper** [comment]
dropping back to 1.2.9.

**Comment by StormJumper** [comment]
So has this been fixed since 1.2.9????

**Comment by mrstan3772** [comment]
> So has this been fixed since 1.2.9????

It seems to have worked well now with version v2.1.0 and latest HDoujin version (Version 2021.12.13.1)

**Comment by HDoujinDownloader** [comment]
There was an attempt to resolve this with HDoujin Downloader v2021.12.13.1 by caching the solution parameters provided by FlareSolverr and sending them along with subsequent requests. This solution works for some websites, but it doesn't resolve issues with others (including webtoon.xyz).

Cloudflare is smart enough to tell when the requests aren't originating from a legitimate web browser. A possible solution would be looking into an alternative to both .NET and cURL's HTTP implementations.
