### ISSUE TITLE
HentaiFox.com issues with downloading

### ISSUE THREAD

**Issue by MimoKar** [HDoujinDownloader/HDoujinDownloader#420]
When downloading from hentaifox server is returning 404 error.

```
14:23:13 hdoujin dow [i] Framework Version: 4.8.9282.0
14:23:13 hdoujin dow [i] OS Version: Microsoft Windows NT 10.0.27729.0 (64-bit)
14:23:13 hdoujin dow [i] Locale: en-GB
14:23:13 hdoujin dow [i] Path: hdoujindownloader\HDoujin Downloader.exe
14:23:13 hdoujin dow [i] Working Directory: hdoujindownloader
14:23:13 hdoujin dow [i] Timestamp: 6. 11. 2024 14:22:04
14:23:13 hdoujin dow [i] Product Version: 2024.10.26.1
14:23:13 hdoujin dow [i] Available Security Protocols: SSL 3.0, TLS 1.0, TLS 1.1, TLS 1.2, TLS 1.3
14:23:13 hdoujin dow [i] Standalone: False
14:23:13 hdoujin dow [i] Repositories: Official Lua Repository, Internal
14:23:13 hdoujin dow [i] Theme: dark
14:23:13 settings    [i] Saving repository metadata
14:23:13 download    [i] Downloading https://i.hentaifox.com/004/3112817/1.jpg
14:23:13 download    [!] An error occurred while downloading https://i.hentaifox.com/004/3112817/1.jpg: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.OpenRead(Uri address)
   at _9qafuJElmLwcKPMdQY4lpVS8oZD.Gsemac.Net.IWebClient.OpenRead(Uri address)
   at _BI9bBgw01wkCpKPcXJqILY0JUJ9._a5DmzlfN4f6S0h3vDo10leEHBTf(_dFUo79iM3YAi7fOzAQkRDt0Jskn , _qLommErCqTogrwqbD2MChvb0mbEA , String , _3J4H3evYAR1B4viuJUvtVC8FTyL )
14:23:13 download    [i] Downloading https://i.hentaifox.com/004/3112817/1.jpg
14:23:13 download    [!] An error occurred while downloading https://i.hentaifox.com/004/3112817/1.jpg: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.OpenRead(Uri address)
   at _9qafuJElmLwcKPMdQY4lpVS8oZD.Gsemac.Net.IWebClient.OpenRead(Uri address)
   at _BI9bBgw01wkCpKPcXJqILY0JUJ9._a5DmzlfN4f6S0h3vDo10leEHBTf(_dFUo79iM3YAi7fOzAQkRDt0Jskn , _qLommErCqTogrwqbD2MChvb0mbEA , String , _3J4H3evYAR1B4viuJUvtVC8FTyL )
14:23:13 download    [i] Downloading https://i.hentaifox.com/004/3112817/1.jpg
14:23:13 download    [!] An error occurred while downloading https://i.hentaifox.com/004/3112817/1.jpg: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.OpenRead(Uri address)
   at _9qafuJElmLwcKPMdQY4lpVS8oZD.Gsemac.Net.IWebClient.OpenRead(Uri address)
   at _BI9bBgw01wkCpKPcXJqILY0JUJ9._a5DmzlfN4f6S0h3vDo10leEHBTf(_dFUo79iM3YAi7fOzAQkRDt0Jskn , _qLommErCqTogrwqbD2MChvb0mbEA , String , _3J4H3evYAR1B4viuJUvtVC8FTyL )
14:23:13 task        [x] Failed to download image https://i.hentaifox.com/004/3112817/1.jpg
14:23:13 download    [i] Downloading https://i.hentaifox.com/004/3112817/2.jpg
14:23:13 download    [!] An error occurred while downloading https://i.hentaifox.com/004/3112817/2.jpg: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.OpenRead(Uri address)
   at _9qafuJElmLwcKPMdQY4lpVS8oZD.Gsemac.Net.IWebClient.OpenRead(Uri address)
   at _BI9bBgw01wkCpKPcXJqILY0JUJ9._a5DmzlfN4f6S0h3vDo10leEHBTf(_dFUo79iM3YAi7fOzAQkRDt0Jskn , _qLommErCqTogrwqbD2MChvb0mbEA , String , _3J4H3evYAR1B4viuJUvtVC8FTyL )
14:23:13 download    [i] Downloading https://i.hentaifox.com/004/3112817/2.jpg
14:23:13 download    [!] An error occurred while downloading https://i.hentaifox.com/004/3112817/2.jpg: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.OpenRead(Uri address)
   at _9qafuJElmLwcKPMdQY4lpVS8oZD.Gsemac.Net.IWebClient.OpenRead(Uri address)
   at _BI9bBgw01wkCpKPcXJqILY0JUJ9._a5DmzlfN4f6S0h3vDo10leEHBTf(_dFUo79iM3YAi7fOzAQkRDt0Jskn , _qLommErCqTogrwqbD2MChvb0mbEA , String , _3J4H3evYAR1B4viuJUvtVC8FTyL )
14:23:13 download    [i] Downloading https://i.hentaifox.com/004/3112817/2.jpg
14:23:13 download    [!] An error occurred while downloading https://i.hentaifox.com/004/3112817/2.jpg: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.OpenRead(Uri address)
   at _9qafuJElmLwcKPMdQY4lpVS8oZD.Gsemac.Net.IWebClient.OpenRead(Uri address)
   at _BI9bBgw01wkCpKPcXJqILY0JUJ9._a5DmzlfN4f6S0h3vDo10leEHBTf(_dFUo79iM3YAi7fOzAQkRDt0Jskn , _qLommErCqTogrwqbD2MChvb0mbEA , String , _3J4H3evYAR1B4viuJUvtVC8FTyL )
14:23:13 task        [x] Failed to download image https://i.hentaifox.com/004/3112817/2.jpg
14:23:13 download    [i] Downloading https://i.hentaifox.com/004/3112817/3.jpg
14:23:13 download    [!] An error occurred while downloading https://i.hentaifox.com/004/3112817/3.jpg: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.OpenRead(Uri address)
   at _9qafuJElmLwcKPMdQY4lpVS8oZD.Gsemac.Net.IWebClient.OpenRead(Uri address)
   at _BI9bBgw01wkCpKPcXJqILY0JUJ9._a5DmzlfN4f6S0h3vDo10leEHBTf(_dFUo79iM3YAi7fOzAQkRDt0Jskn , _qLommErCqTogrwqbD2MChvb0mbEA , String , _3J4H3evYAR1B4viuJUvtVC8FTyL )
```
It is happening on new galleries ...

**Comment by MimoKar** [comment]
I think I know where is the problem. Downloader is looking for JPG, but images are available in new galleries as WebP...

**Comment by MimoKar** [comment]
I temporarily fixed by this in hentaifox.lua:

```
        if(pageExtension == 'p') then
            pageExtension = '.png'
        elseif(pageExtension == 'g') then
            pageExtension = '.gif'
		elseif(pageExtension == 'w') then
            pageExtension = '.webp'	
        else
            pageExtension = '.jpg'
        end
```

**Comment by HDoujinDownloader** [comment]
You were correct. I uploaded your proposed fix, and everything should be working normally again!
