### ISSUE TITLE
Add FlareSolverr Native Support for Linux Systems 

### ISSUE THREAD

**Issue by mrstan3772** [HDoujinDownloader/HDoujinDownloader#49]
**Version:** 2021.12.13.1
**Component**: FlareSolverr v2.1.0
**Platform**: Linux (Debian Distribution)
**URL**:  https://www.webtoon.xyz/

I noticed the following error message in the log files : 

`10:32:43 download    [i] Downloading https://cdn3.webtoon.xyz/manga_6173b6f054a49/chapter-1/01.jpg
10:32:43 hdoujinchal [i] Using FlareSolverrChallengeHandler
10:32:43 flaresolver [i] Starting FlareSolverr service
10:32:43 flaresolver [x] Unable to locate FlareSolverr executable. Download FlareSolverr at https://github.com/FlareSolverr/FlareSolverr/releases/latest
10:32:43 hdoujinchal [x] System.Net.WebException: The challenge solver threw an exception. ---> System.IO.FileNotFoundException: Could not find FlareSolverr executable.
   at kfMtuTtZdOmRddmHXGySkphWuIrm.nWoFYCxTioCnwKjaFLWlbjYkfKuv()
   at kfMtuTtZdOmRddmHXGySkphWuIrm.foJAOjMEbbnJePRTjEpHBEQgJcTD()
   at kfMtuTtZdOmRddmHXGySkphWuIrm.nSDgoGNDhmAPQKkxoPrdwKHLwktO()
   at kfMtuTtZdOmRddmHXGySkphWuIrm.RdahbrtYAwMMwxNHGIVWcxPMSnFM(hVDRNBNaaGSizdxFIuWwloDBLSSs , Boolean )
   at kfMtuTtZdOmRddmHXGySkphWuIrm.NZITSjzHneSWzRlOChfJxMkGgHuC(hVDRNBNaaGSizdxFIuWwloDBLSSs )
   at kYfGogInpIdJijaVBOmJCJyXUtmvA.DaTQFFRFYTfxQgGCxjZFBLYesEmcA(nQpcxHenkMfJClBWpcWHzPRqtNDN , Exception , CancellationToken )
   at dlgxFmpVwnKGsMLGopxffeAXhMOK.GAZEZBWUpAUOCJjnDnJxrGlhbdYR.GduvVVwpJwSpyKNWEAuJgyPwkfSEA(nQpcxHenkMfJClBWpcWHzPRqtNDN )
   at pEonsEtpajQXXmmfYUBzqwHRMiaP.YPATBcQvQAKbDZqyPHNwKiYaVIwc()
   at TtvUvvoYhjLhLaBXJyZaIGZjFJLG.HWZaQbRFtoGkiprIhgqsjptqJKHR(WebRequest , CancellationToken )
   at JnjOPBlhnxvNranJDqWxtugTNKvW.HWZaQbRFtoGkiprIhgqsjptqJKHR(WebRequest , CancellationToken )
   at gtaBSqcMogHxiSuAgEMCyBWIBaIGb.HWZaQbRFtoGkiprIhgqsjptqJKHR(nQpcxHenkMfJClBWpcWHzPRqtNDN , CancellationToken )
   at dlgxFmpVwnKGsMLGopxffeAXhMOK.HWZaQbRFtoGkiprIhgqsjptqJKHR(nQpcxHenkMfJClBWpcWHzPRqtNDN , CancellationToken )
   --- End of inner exception stack trace ---
   at dlgxFmpVwnKGsMLGopxffeAXhMOK.HWZaQbRFtoGkiprIhgqsjptqJKHR(nQpcxHenkMfJClBWpcWHzPRqtNDN , CancellationToken )
   at gtaBSqcMogHxiSuAgEMCyBWIBaIGb.HWZaQbRFtoGkiprIhgqsjptqJKHR(WebRequest , CancellationToken )
   at JnjOPBlhnxvNranJDqWxtugTNKvW.HWZaQbRFtoGkiprIhgqsjptqJKHR(WebRequest , CancellationToken )
   at AqeXEpPKvhkJaKASUvuIDARGIFvN.DaTQFFRFYTfxQgGCxjZFBLYesEmcA(nQpcxHenkMfJClBWpcWHzPRqtNDN , Exception , CancellationToken )`

**Comment by HDoujinDownloader** [comment]
Out of curiosity, does it work if you start FlareSolverr manually? HDD should be able to detect that it's running, so this could be a temporary workaround.

**Comment by mrstan3772** [comment]
Urls no longer work for the webtoon.xyz website. Module update required.

**Comment by HDoujinDownloader** [comment]
There was a typo in the `Madara.lua` module that has now been fixed, so you should be able to add URLs to the download queue now.

But there's another problem now: When attempting to download the images, FlareSolverr gets hit with a `Error 1020` page from Cloudflare. I think this is because FlareSolverr v2.0.0+ doesn't allow the HTTP headers to be modified, so no `referer` header can be sent with the request. It looks like we're not the first to encounter this problem, as FlareSolverr/FlareSolverr#254 seems to be related.

This is a difficult problem to resolve right now, but we'll see how the FlareSolverr dev responds. :thinking: I might open a new issue myself.

**Comment by mrstan3772** [comment]
> There was a typo in the `Madara.lua` module that has now been fixed, so you should be able to add URLs to the download queue now.
> 
> But there's another problem now: When attempting to download the images, FlareSolverr gets hit with a `Error 1020` page from Cloudflare. I think this is because FlareSolverr v2.0.0+ doesn't allow the HTTP headers to be modified, so no `referer` header can be sent with the request. It looks like we're not the first to encounter this problem, as [FlareSolverr/FlareSolverr#254](https://github.com/FlareSolverr/FlareSolverr/issues/254) seems to be related.
> 
> This is a difficult problem to resolve right now, but we'll see how the FlareSolverr dev responds. 🤔 I might open a new issue myself.
> 
> **Edit:** Opened a new issue: [FlareSolverr/FlareSolverr#266](https://github.com/FlareSolverr/FlareSolverr/issues/266)

All right then I'll go back to the previous version. You have to manually start FlareSolverr for linux and think about execution permission.
