### ISSUE TITLE
Maximum timeout reached

### ISSUE THREAD

**Issue by mrstan3772** [HDoujinDownloader/HDoujinDownloader#60]
Version 2022.1.3
Component: FlareSolverr v1.2.9
Platform: Linux (Debian Distribution) || Windows 10
Site: https://www.webtoon.xyz/

I got this error:

```
18:37:35 hdoujinchal [x] System.Net.WebException: The challenge solver threw an exception. ---> afHjInmTsQxoiLqMAiJMENuahgnaA: Failed to execute FlareSolverr command. ---> System.Net.WebException: La demande a été abandonnée : Le délai d'attente de l'opération a expiré..
   à System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   à System.Net.WebClient.UploadString(Uri address, String method, String data)
   à geaWYoSJClStyLEisGZqBlTeCAHT.Gsemac.Net.IWebClient.UploadString(Uri address, String data)
   à MFKEaMZjkLMutBNFBXdrIvmiGQSt.MwEeLqDJeNlfEStnMlqHbNJoYdrSA(TZNgPAKdlPnVdOLXQTXLlHChlAnaA , Boolean )
   à AyhvopkTaVGwcYRDXBxojPlxBxBT.bZNdDCvVHMiAMKIAhZUyhjZKRATwA(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , Exception , CancellationToken )
   --- Fin de la trace de la pile d'exception interne ---
   à AyhvopkTaVGwcYRDXBxojPlxBxBT.bZNdDCvVHMiAMKIAhZUyhjZKRATwA(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , Exception , CancellationToken )
   à DIyBwRXrbgAcRcGdAnWEKsAhyyFv.opCRWpkqwPduNzNaFGXTcgvKNOxg()
   à fXvQSqEcFwfaRGnRXEdLwQWDzZks.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   à PmKpnXYbqSjigeGoHwIATVdDpfWA.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   --- Fin de la trace de la pile d'exception interne ---
   à PmKpnXYbqSjigeGoHwIATVdDpfWA.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   à APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à uuoaNorlsetLwkNGECqbbdEahRArA.bZNdDCvVHMiAMKIAhZUyhjZKRATwA(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , Exception , CancellationToken )
18:37:35 http        [x] Exception was thrown when accessing https://www.webtoon.xyz/read/my-kingdom-silent-war/: System.Net.WebException: The challenge solver threw an exception. ---> System.Net.WebException: The challenge solver threw an exception. ---> afHjInmTsQxoiLqMAiJMENuahgnaA: Failed to execute FlareSolverr command. ---> System.Net.WebException: La demande a été abandonnée : Le délai d'attente de l'opération a expiré..
   à System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   à System.Net.WebClient.UploadString(Uri address, String method, String data)
   à geaWYoSJClStyLEisGZqBlTeCAHT.Gsemac.Net.IWebClient.UploadString(Uri address, String data)
   à MFKEaMZjkLMutBNFBXdrIvmiGQSt.MwEeLqDJeNlfEStnMlqHbNJoYdrSA(TZNgPAKdlPnVdOLXQTXLlHChlAnaA , Boolean )
   à AyhvopkTaVGwcYRDXBxojPlxBxBT.bZNdDCvVHMiAMKIAhZUyhjZKRATwA(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , Exception , CancellationToken )
   --- Fin de la trace de la pile d'exception interne ---
   à AyhvopkTaVGwcYRDXBxojPlxBxBT.bZNdDCvVHMiAMKIAhZUyhjZKRATwA(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , Exception , CancellationToken )
   à DIyBwRXrbgAcRcGdAnWEKsAhyyFv.opCRWpkqwPduNzNaFGXTcgvKNOxg()
   à fXvQSqEcFwfaRGnRXEdLwQWDzZks.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   à PmKpnXYbqSjigeGoHwIATVdDpfWA.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   --- Fin de la trace de la pile d'exception interne ---
   à PmKpnXYbqSjigeGoHwIATVdDpfWA.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   à APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à uuoaNorlsetLwkNGECqbbdEahRArA.bZNdDCvVHMiAMKIAhZUyhjZKRATwA(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , Exception , CancellationToken )
   à DIyBwRXrbgAcRcGdAnWEKsAhyyFv.opCRWpkqwPduNzNaFGXTcgvKNOxg()
   à fXvQSqEcFwfaRGnRXEdLwQWDzZks.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à EDvCRNwEFITnqfPJWdCsdHryLZAX.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à qnYYRkMoIaAMXwNQSriSnITgTYWA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   à DDQIzAFVmHzQuaJVvZhBGyhnACdJ.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   à APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   à PmKpnXYbqSjigeGoHwIATVdDpfWA.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   --- Fin de la trace de la pile d'exception interne ---
   à PmKpnXYbqSjigeGoHwIATVdDpfWA.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   à APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   à SVlelqdAVtHOBKzMwEFXGHelfkwG.xXHcVylqtvXCcPCbzjOFNuLGSySc(ZMxkCKElMDQPKLOYvBjyZKXMNJsd , CancellationToken )
   à APaMSxeSvtnEuAsOyBPhvTLwtyvm.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à vrjDNCJRkasqxcELTWZQCTvpJYOOA.xXHcVylqtvXCcPCbzjOFNuLGSySc(WebRequest , CancellationToken )
   à ANkQshBKCTJBLlAYVGxknznGGiFd.wwjGYLdpLXvZBBXeZEBQozkDwQSoA(String , CookieContainer , String[] , String , wJhZKjMhUlAAOrHmtApKIGEADPnVA , String[] )
```
In FlareSolver REPL:

```
2022-01-11T18:40:59+01:00 ERROR REQ-4 Error: Maximum timeout reached. maxTimeout=100000 (ms)
    at C:\snapshot\FlareSolverr\node_modules\await-timeout\src\utils.js:20:38
    at Timeout.<anonymous> (C:\snapshot\FlareSolverr\node_modules\await-timeout\src\index.js:32:46)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
2022-01-11T18:44:15+01:00 ERROR REQ-4 Unable to process browser request. Error: Error: Maximum timeout reached. maxTimeout=100000 (ms)
```

Working with FlareSolverr v2+ but can't download images.

**Comment by mrstan3772** [comment]
The challenge fails to resolve even with a 300ms timeout.
I noticed on v2 version, when challenge fail multiple time it skips a bookmark or download in the list. You have to look in the logs to know that the download failed, it's not easy. 

After failures on the same url the challenge manages to be resolved on the next but the same problem is redundant.
I don't know why he has to solve different challenges with the same session to browse urls on the identical site.

The site is protected with the cloudflare anti bot system.
Some pages are inaccessible or only once from the browser.

The 1020 error is describe  : 

"While visiting a site protected by Cloudflare, error 1020 “Access denied (Error: 1020)” indicates you’ve violated a Firewall Rule. When this happens, you’ll see the error “Access Denied (Error: 1020)” and your request was blocked by the filter based Firewall rule on the site. If you’re the site owner, you can find the requests that was blocked by the Firewall on the Firewall page under the Events menu."

So my script only partially works. I decided to produce the pages based on the Data URI scheme

I use puppeteer, puppeteer-cluster and some extra (puppeteer-extra-plugin-stealth) with node.js language .

Headless mode not working and cloudflare take some time to resolve challenge. 

I disable security on web navigator to get uri scheme (CORS policy). 

Puppeteer args:

```
args: [
   '--disable-features=IsolateOrigins', 
   '--disable-site-isolation-trials',
   '--disable-web-security',
   '--no-sandbox',
],
```
I decode the content to get buffer file and download on my storage space.

The website use lazy loading, i am constrained scrolling on the bottom of the page with puppeteer. It's take more time with no parallel requests.

The only unstoppable solution against firewalls, scrappers and other anti bot systems is to retrieve the content buffer rather than an url if the page managed to load (realistic web browser).

My biggest problem is getting the system work in headless mode.

If you have another ideas.

**Comment by HDoujinDownloader** [comment]
> You have to look in the logs to know that the download failed, it's not easy.

If I understand correctly, this is because HDoujin Downloader does not report that an error has occurred until after the download has finished. I could add a setting to make the download fail as soon as any of the images fail, which should help with this (#62).

> I don't know why he has to solve different challenges with the same session to browse urls on the identical site

With this website in particular, it's because it encounters the 1020 error and figures that there's a challenge that needs solving. Sometimes this isn't an explicit challenge, but a result of the request being blocked due to not originating from a legitimate web browser, which FlareSolverr resolves. However, since FlareSolverr v2.0.0+ can't be used to download images anymore, each one still fails even though the request gets through just fine.

> So my script only partially works. I decided to produce the pages based on the Data URI scheme

This is smart, and how previous versions of FlareSolverr did it-- It just converted the requested file to a Base64 string and returned that. According to the FlareSolverr dev, puppeteer + Firefox does not allow this method (earlier versions of FlareSolverr used Chrome instead).

It might be time to ditch FlareSolverr and use a web driver + a stealth plugin as you're describing. This could work, but it will take some effort get working with .NET Framework 4.0. I'll continue thinking on it.
